### ISSUE TITLE
G4mespeed + fixed speed + block event separator = crash

### ISSUE THREAD

**Issue by Sussy-OS** [SpaceWalkerRS/block-event-separator#3]
Hello there, SpaceWalker. With the latest version of G4mespeed, I turned the tps to 0.156, set animation to fixed speed, then pressed m to reset the tickspeed, and boom, minecraft crashed. 

```
[11:51:54] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2338.method_10263()" because "$$0" is null
	at net.minecraft.class_1923.method_37232(class_1923.java:61) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.tickMovingBlocks_bes(class_1937.java:1151) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.tickFixedSpeed_bes(class_310.java:3166) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.handler$zzl000$block-event-separator$tickFixedSpeed(class_310.java:3107) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1941) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1150) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) ~[Fabric%201.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[Fabric%201.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
```

**Comment by SpaceWalkerRS** [comment]
Thanks for the report! I've been having trouble figuring out what the issue is, when I stumbled upon a very similar issue with [Lithium](https://github.com/CaffeineMC/lithium-fabric/issues/473). Do you happen to be running Lithium? If so, can you try removing it and see if the issue persists?

**Comment by Sussy-OS** [comment]
I do happen to have Lithium, I will attempt to remove it, and try again. Keep in mind, I can still use block event separator fine, even with Lithium installed. Only when I turn fixed speed on in G4mespeed does it crash.

**Comment by 2No2Name** [comment]
Lithium allows certain block entities to sleep by temporarily replacing their block entity ticker with a dummy ticker. The dummy ticker does not return a non-null position, because it doesn't have a reference to the block entity.

**Comment by 2No2Name** [comment]
Adding a null check here should work around it: https://github.com/SpaceWalkerRS/block-event-separator/blob/337f9ce425306629c21e7431059b11b05a12027c/src/main/java/block/event/separator/mixin/client/LevelMixin.java#LL53C2-L53C2

`if (pos==null)
    continue`

**Comment by Sussy-OS** [comment]
> Thanks for the report! I've been having trouble figuring out what the issue is, when I stumbled upon a very similar issue with [Lithium](https://github.com/CaffeineMC/lithium-fabric/issues/473). Do you happen to be running Lithium? If so, can you try removing it and see if the issue persists?

Oh yeah, forgot about this. I removed Lithium, and was not able to reproduce the bug anymore.
